import = [
  "~/.config/alacritty/themes/themes/catppuccin_mocha.toml"
]

[env]
TERM = "xterm-256color"

[window]
padding.x = 0 
padding.y = 0
decorations = "ButtonLess"
opacity = 0.65 
blur = false 
option_as_alt = "Both"
startup_mode = "Maximized"

[scrolling]
multiplier = 2

[colors]
draw_bold_text_with_bright_colors = true

[font]
normal.family = "Maple Mono NF"
normal.style = "Light"

bold.family = "Maple Mono NF"
bold.style = "Bold"

italic.family = "Maple Mono NF"
italic.style = "Italic"

bold_italic.family = "Maple Mono NF"
bold_italic.style = "BoldItalic"
size = 16

[cursor]
style.blinking = "Always"
style.shape ="Block"
vi_mode_style.shape = "Block"
vi_mode_style.blinking = "Always"
blink_interval = 250
blink_timeout = 0

[mouse]
hide_when_typing = true

[keyboard]
bindings = [
  {key = "f", mods="Super", action="ToggleSimpleFullscreen"},
  {key= "t", mods= "Control", action= "CreateNewTab"}
]

[selection]
save_to_clipboard = true

[shell]
program = "/bin/zsh"
