import = [
  "~/.config/alacritty/themes/themes/eldritch.toml"
]

[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10
decorations = "ButtonLess"
# opacity = 0.35
opacity = 0.97
blur = false 
option_as_alt = "Both"
startup_mode = "SimpleFullScreen"

[scrolling]
multiplier = 2

[colors]
draw_bold_text_with_bright_colors = true

[font]
normal.family = "CommitMono Nerd Font Mono"
normal.style = "Regular"

bold.family = "CommitMono Nerd Font Mono"
bold.style = "Bold"

italic.family = "CommitMono Nerd Font Mono"
italic.style = "Italic"

bold_italic.family = "CommitMono Nerd Font Mono"
bold_italic.style = "BoldItalic"
size = 14.75
# size = 15


[cursor]
style.blinking = "Always"
style.shape ="Block"
vi_mode_style.shape = "Block"
vi_mode_style.blinking = "Always"
blink_interval = 250
blink_timeout = 0

[mouse]
hide_when_typing = true

[keyboard]
bindings = [
  {key = "f", mods="Super", action="ToggleSimpleFullscreen"},
  # {key= "t", mods= "Control", action= "CreateNewTab"}
]

[selection]
save_to_clipboard = true

[shell]
program = "/bin/zsh"
