import = [
  "~/.config/alacritty/themes/themes/rose-pine-moon.toml"
]

shell = { program = "/bin/zsh", args = ["-c", "TERM=xterm-256color nvim --cmd 'set termguicolors' --cmd 'hi Normal ctermbg=NONE guibg=NONE' --cmd 'hi NonText ctermbg=NONE guibg=NONE' --cmd 'hi EndOfBuffer ctermbg=NONE guibg=NONE'"] }

[env]
TERM = "xterm-256color"

[window]
padding.x=0
padding.y=0

decorations = 'Buttonless'

opacity = 0.4
blur = true 

option_as_alt = "Both"


dimensions = { columns = 160, lines = 60 }
position = { x = 0, y = 0 }

[font]
normal.family = "JetBrainsMonoNL Nerd Font"
size = 15


